{% set name = "cnsr" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cnsr-{{ version }}.tar.gz
  sha256: d7adb17787dc6e8596f242a475fdd401e108e4902bc825ec687650aba6917f18

build:
  entry_points:
    - cnsr_copy_notebooks = cnsr.install:copy_notebooks
    - install_cnsr_launcher_data = cnsr.install:install_cnsr_launcher_data
  noarch: python
  number: 2
  script:
    - {{ PYTHON }} -m pip install . -vv
    - {{ PYTHON }} -m cnsr.install {{ PREFIX }}

requirements:
  host:
    - python >=3.9
    - setuptools >=61
    - pip
    - click <9.0a0
    - ipyfilechooser <1.0a0
    - ipywidgets <9.0a0
  run:
    - python >=3.9
    - click <9.0a0
    - ipyfilechooser <1.0a0
    - ipywidgets <9.0a0
    - jupyter_app_launcher >=0.1,<1.0a0
    - jupyterlab >=3.1,<4.0a0
    - matplotlib-base <4.0a0
    - mne <2.0a0
    - mne-nirs <1.0a0
    - neurokit2 <1.0a0
    - nilearn <1.0a0
    - numpy <2.0a0
    - openpyxl <4.0a0
    - pandas <3.0a0

test:
  imports:
    - cnsr
  commands:
    - pip check
    - cnsr_copy_notebooks --help
    - install_cnsr_launcher_data --help
  requires:
    - pip

about:
  summary: Lab code package for the CNSR lab at Heidelberg University
  home: https://github.com/ssciwr/cnsr
  license: MIT
  license_file:
    - COPYING.md
    - LICENSE.md

extra:
  recipe-maintainers:
    - TorstenWuestenberg
    - dokempf
